name: Build Docker Image & Test

on:
  push:
    branches:
      - "server"
  pull_request:

jobs:
  build-and-push-docker-image:
    runs-on: docker-builder-fast # has to run on docker-builder
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # need for docker build
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/44ai-mineru
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  export-sha:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.export.outputs.short_sha }}
    steps:
      - name: Export short SHA
        id: export
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

  test:
    needs: [export-sha, build-and-push-docker-image]
    runs-on: self-hosted-fast
    container:
      image: 44ai/44ai-mineru:sha-${{ needs.export-sha.outputs.short_sha }}
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        # I found the 32g in the paddle paddle file which is the memory issue :-)
      options: --shm-size=32g # otherwise we get a bus error (core dumped), do not ask me how long it took to debug this :-)
    name: test
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: run test in docker
        # all the files are stored in /
        run: |
          magic-pdf --help

  tests-k8s:
    runs-on: self-hosted-fast # has to run on a github hosted runner
    needs: build-and-push-docker-image
    env:
      NAMESPACE: mineru-44ai # same as production, as for redis service dns resolver
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get short commit SHA
        id: vars
        run: echo "::set-output name=short_sha::${GITHUB_SHA::7}"
      - name: Current Image Tag
        run: |
          echo "image tag sha-${{ steps.vars.outputs.short_sha }}"
      - name: Install dependecies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget git
      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
      - name: Create k3d cluster
        run: |
          k3d cluster create mycluster --wait --port "30001:30001@server:0"
      - name: Get kubeconfig
        run: |
          k3d kubeconfig get mycluster > kubeconfig.yaml
          cat kubeconfig.yaml
      - name: Set KUBECONFIG environment variable
        run: echo "KUBECONFIG=$(pwd)/kubeconfig.yaml" >> $GITHUB_ENV
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
      - name: Get Nodes & Infos
        run: |
          kubectl get pods --all-namespaces
      - name: Set KUBECONFIG environment variable
        run: echo "KUBECONFIG=$(pwd)/kubeconfig.yaml" >> $GITHUB_ENV
      - name: Create namespace
        run: |
          kubectl create namespace $NAMESPACE
      - name: Create DockerHub secret file
        # This step writes the YAML from your GitHub secret into k8s/dockerhub-secret.yaml
        run: |
          echo "${{ secrets.DOCKERHUB_SECRET_FILE }}" > k8s/dockerhub-secret.yaml
      - name: Install Dockerhub secret
        run: |
          kubectl apply -f k8s/dockerhub-secret.yaml -n $NAMESPACE
      # we replace the image tag with the current one
      - name: Install MinerU
        run: |
          sed -i 's|44ai/44ai-mineru:main|44ai/44ai-mineru:sha-${{ steps.vars.outputs.short_sha }}|g' k8s/deploy.yaml
          kubectl apply -f k8s/deploy.yaml -n $NAMESPACE
      - name: Wait until Mineru Container is ready (downloaded)
        run: |
          echo "Describing pod for debugging (10 times, 5s apart)..."
          for i in $(seq 1 10); do
            echo "===> Describe attempt #$i"
            kubectl describe pod -l app=mineru-44ai -n $NAMESPACE
            sleep 10
          done

          kubectl wait --for=condition=ready pod -l app=mineru-44ai -n $NAMESPACE --timeout=1200s
          kubectl get pods -n $NAMESPACE

      - name: Get Cluster IP
        id: cluster-ip
        run: |
          CLUSTER_IP=127.0.0.1
          echo "Using Cluster IP: $CLUSTER_IP"
          echo "cluster_ip=$CLUSTER_IP" >> $GITHUB_OUTPUT
      - name: Wait until server is started
        run: |
          echo "Waiting for server to start..."
          sleep 30
      - name: Download Test Files
        run: |
          curl -O https://raw.githubusercontent.com/44ai-labs/MinerU/server/demo/small_ocr.pdf
      - name: Simple PDF Test
        run: |
          CLUSTER_IP="${{ steps.cluster-ip.outputs.cluster_ip }}"
          echo "Using Cluster IP: $CLUSTER_IP"
          curl -X POST "http://$CLUSTER_IP:30001/analyze-file" -F "file=@small_ocr.pdf;type=application/pdf"

      - name: Copy Logs
        if: always()
        run: |
          ./scripts/copy_logs.sh
      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/